### ISSUE TITLE
关于MAPPO中Gradient clip 参数设置的问题

### ISSUE THREAD

**Issue by shelby-ce** [Lizhi-sjtu/MARL-code-pytorch#1]
请问在MAPPO的Trick 7: Gradient clip里面，max_norm = 10？而在PPO中这个值被设为0.5

**Comment by Lizhi-sjtu** [comment]
您好，MAPPO里的10我是按照MAPPO原论文设定的，PPO里的0.5只是一个经验值，这个是可以调整的



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: shelby-ce ***@***.***&gt;
发送时间: 2022年8月10日 11:03
收件人: Lizhi-sjtu/MARL-code-pytorch ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: Re: [Lizhi-sjtu/MARL-code-pytorch] 关于MAPPO中Gradient clip 参数设置的问题 (Issue #1)





 
请问在MAPPO的Trick 7: Gradient clip里面，max_norm = 10？而在PPO中这个值被设为0.5

**Comment by shelby-ce** [comment]
谢谢您的回复 ^_^
