### ISSUE TITLE
MAPPO如何Decentrolised Execute

### ISSUE THREAD

**Issue by ErwinLiYH** [Lizhi-sjtu/MARL-code-pytorch#18]
您好 非常感谢这版MAPPO代码，

但是我有一个疑问，MAPPO中的Actor输入是所有Agent的Observation，输出是所有Agent的动作概率，那他如何Decentrolised Execute呢？

**Comment by yuanjialegithub** [comment]
我也有这个疑问，请问是要修改代码的执行逻辑吗？
